import { auth, db, provider, ADMIN_EMAIL } from './firebase/config.js';
import { onAuthStateChanged, signInWithPopup, signInWithRedirect, getRedirectResult, signOut } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { ref, get, set, update, remove, push, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js';
import { logEvent } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-analytics.js';
import katex from 'https://cdn.jsdelivr.net/npm/katex@0.16.22/+esm';

const $ = s => document.querySelector(s), app = $('#app');
const state = { user:null, formulas:[], progress:{}, stats:null, page:'home', session:null, selected:null, theme:localStorage.getItem('formulus-theme') || 'light' };
document.documentElement.dataset.theme = state.theme;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const formulaHtml = text => { try { return katex.renderToString(text || '', { throwOnError:false, displayMode:true }); } catch { return esc(text); } };
const notify = (msg, error=false) => { const t=$('#toast'); t.textContent=msg; t.className=error?'show error':'show'; clearTimeout(notify.timer); notify.timer=setTimeout(()=>t.className='',3600); };
const today = () => new Date().toLocaleDateString('en-CA');
const dayGap = date => date ? Math.round((new Date(today())-new Date(date))/86400000) : 99;
const subjects = ['Mathematics','Physics','Chemistry'];
const AI_EXTRACTION_PROMPT = String.raw`You are a formula extraction and structuring AI for an app called Formulus.

I will provide you with a PDF, image, screenshot, formula sheet, short notes, textbook page, handwritten notes, or other study material.

Your job is to carefully analyze the provided material, identify every important mathematical, physics, or chemistry formula, equation, identity, relation, law, or standard result, and convert them into the exact JSON format required by my Formulus app.

REQUIRED OUTPUT FORMAT

Your entire response must contain ONLY a valid JSON array. Do not include Markdown, code fences, explanations, comments, headings, or extra text.

Each formula must be represented exactly like this:
[
  {
    "title": "Formula Name",
    "hint": "Short explanation of what the formula is used for",
    "formula": "LaTeX formula",
    "conditions": "Conditions, restrictions, definitions, or important variable information"
  }
]

FIELD REQUIREMENTS

1. title: Give the formula a clear, concise, descriptive name. If the source contains genuinely useful multiple forms of the same formula, include separate entries with distinct titles.

2. hint: Write a short, useful description explaining what the formula represents or when it is useful. Do not simply repeat the title.

3. formula: Write the formula using LaTeX syntax so it can be rendered by KaTeX or MathJax. Because the output is JSON, every LaTeX backslash MUST be escaped. For example, write "\\frac{a}{b}" in the JSON output, not "\frac{a}{b}".

4. conditions: Include useful restrictions, assumptions, definitions of variables, or special conditions. If there are no meaningful special conditions, use a concise description such as "Valid for all real x". Do not invent unnecessary restrictions.

WHAT TO EXTRACT

Extract useful revision material: standard formulas; fundamental equations; algebraic and trigonometric identities; geometric relations; calculus, coordinate geometry, probability, statistics, sequence and series formulas; physics laws and equations; chemistry equations and relations; important mathematical results; definitions conventionally expressed as equations; common special cases; and important derived formulas explicitly present in the source.

DO NOT EXTRACT

Do not create entries for ordinary explanatory sentences, random numerical substitutions, repeated formulas, decorative equations, page or question numbers, labels, diagrams without a meaningful formula, or text that merely contains symbols but is not a useful result. Include repeated formulas only once unless their conditions or forms differ meaningfully.

PRESERVE THE SOURCE ACCURATELY

Do not change mathematical meaning. Pay particular attention to fractions, exponents, subscripts, parentheses, roots, plus/minus signs, Greek letters, integrals, summations, limits, derivatives, vectors, absolute values, logarithms, trigonometric functions, units, inequalities, and domain restrictions. For images or scanned PDFs, inspect the visual content rather than relying only on imperfect OCR.

HANDWRITTEN OR UNCLEAR FORMULAS

If a formula is slightly unclear but can be confidently reconstructed from context, reconstruct it correctly. If it is genuinely impossible to determine with reasonable confidence, do not invent it.

MULTIPLE SUBJECTS AND ORDER

If the uploaded material contains multiple subjects or chapters, extract all relevant formulas in one flat JSON array. Keep formulas approximately in the logical order in which they appear; if the source is poorly organized, arrange them in a sensible revision order.

QUALITY CHECK BEFORE RESPONDING

Silently verify that every important formula was considered, duplicates were removed, notation and LaTeX are valid, all LaTeX backslashes and quotation marks are correctly escaped for JSON, and every object contains exactly title, hint, formula, and conditions. The final output must be valid JSON with absolutely no text outside the JSON array.

FINAL RESPONSE RULE

Return ONLY the JSON array. Do not say "Here are the formulas." Do not use a json code fence. The output must be directly copy-pasteable into the Formulus formula uploader.`;

function shell(content, page=state.page) {
 const nav = [['home','⌂','Home'],['subjects','▦','Subjects'],['easy','●','Easy'],['needPractice','◐','Practice'],['forgot','●','Forgot'],['profile','◉','Profile']];
 if (isAdmin()) nav.push(['admin','⚙','Admin']);
 app.innerHTML=`<main class="app-shell"><header class="top"><button class="brand" data-go="home" aria-label="Formulus home"><img src="assets/logo.png" alt="" onerror="this.remove()"><span class="brand-mark">ƒ</span><b>Formulus</b></button><button class="theme" aria-label="Toggle colour theme">${state.theme==='dark'?'☀':'☾'}</button></header><section class="view">${content}</section><nav class="bottom">${nav.map(([id,icon,label])=>`<button class="${page===id?'active':''}" data-go="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav></main>`;
 bindShell();
}
function bindShell(){ document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go)); $('.theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('formulus-theme',state.theme);document.documentElement.dataset.theme=state.theme;render();}; }
function login(){ app.innerHTML=`<main class="login"><div class="login-card"><img class="login-logo" src="assets/logo.png" alt="Formulus logo" onerror="this.style.display='none'"><p class="eyebrow">FORMULUS</p><h1>Remember formulas.<br>Master JEE.</h1><p>Revise smarter with active recall — one hint, one formula, at a time.</p><button id="google" class="google"><span>G</span>Continue with Google</button><small>Personal progress. No distractions. Pick up anywhere.</small></div></main>`; $('#google').onclick=async()=>{try{await signInWithPopup(auth,provider);}catch(e){console.error(e);if(e.code==='auth/popup-blocked') { await signInWithRedirect(auth,provider); } else notify('Couldn’t sign in. Please try again.',true);}}; }
function isAdmin(){return state.user?.email?.toLowerCase()===ADMIN_EMAIL;}
async function bootstrap(user){state.user=user; try { await update(ref(db,`users/${user.uid}`),{displayName:user.displayName||'Student',email:user.email||'',photoURL:user.photoURL||'',createdAt:serverTimestamp(),lastLogin:serverTimestamp()}); await loadData(); navigate('home'); } catch(e){console.error(e); notify('Couldn’t load your revision data. Check your connection.',true); navigate('home');}}
async function loadData(){ const [f,p,s]=await Promise.all([get(ref(db,'formulas')),get(ref(db,`userProgress/${state.user.uid}`)),get(ref(db,`userStats/${state.user.uid}`))]); state.formulas=flatten(f.val()); state.progress=p.val()||{}; state.stats=s.val()||blankStats(); }
const blankStats=()=>({totalReviewed:0,easyCount:0,needPracticeCount:0,forgotCount:0,currentStreak:0,lastRevisionDate:''});
function flatten(data){let out=[]; Object.entries(data||{}).forEach(([subject,chapters])=>Object.entries(chapters||{}).forEach(([chapter,items])=>Object.entries(items||{}).forEach(([id,f])=>out.push({...f,id,subject,chapter})))); return out.sort((a,b)=>a.subject.localeCompare(b.subject)||a.chapter.localeCompare(b.chapter)||(a.order||0)-(b.order||0));}
function navigate(page, data=null){state.page=page; if(data)state.selected=data; render();window.scrollTo(0,0);}
function render(){ if(!state.user)return login(); if(state.page==='home')return home(); if(state.page==='subjects')return subjectsPage(); if(['easy','needPractice','forgot'].includes(state.page))return bucketPage(state.page); if(state.page==='chapter')return chapterPage(); if(state.page==='revision')return revisionPage(); if(state.page==='complete')return completePage(); if(state.page==='profile')return profile(); if(state.page==='admin'&&isAdmin())return admin(); navigate('home'); }
function counts(list=state.formulas){let c={easy:0,needPractice:0,forgot:0,reviewed:0};list.forEach(f=>{let x=state.progress[f.id]?.status;if(x){c[x]++;c.reviewed++;}});return c;}
function home(){const c=counts(), name=esc((state.user.displayName||'Student').split(' ')[0]); shell(`<div class="hero"><p class="eyebrow">YOUR DAILY REVISION</p><h1>Good day, ${name} <span>👋</span></h1><div class="streak"><span>🔥</span><div><small>Current streak</small><b>${state.stats.currentStreak||0} ${state.stats.currentStreak===1?'day':'days'}</b></div></div></div><button class="quick-card" id="quick"><span>⚡</span><div><b>Quick Revision</b><small>Pick a focused set and start now</small></div><i>›</i></button><section class="section"><h2>Your revision</h2><div class="stat-grid">${stat('easy','●','Easy',c.easy)}${stat('needPractice','●','Need Practice',c.needPractice)}${stat('forgot','●','Forgot',c.forgot)}</div></section><section class="section"><div class="heading"><h2>Subjects</h2><button class="text" data-go="subjects">See all</button></div><div class="subject-list">${subjects.map((s,i)=>`<button class="subject" data-subject="${s}"><span>${['⌗','⚡','⚗'][i]}</span><div><b>${s}</b><small>${state.formulas.filter(f=>f.subject===s).length} formulas</small></div><i>›</i></button>`).join('')}</div></section>`); $('#quick').onclick=quickModal; document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>navigate('chapter',{subject:b.dataset.subject,overview:true})); }
const stat=(bucket,icon,label,n)=>`<button class="stat ${bucket}" data-go="${bucket}"><span>${icon}</span><b>${n}</b><small>${label}</small></button>`;
function subjectsPage(){shell(`<div class="page-title"><p class="eyebrow">FORMULA LIBRARY</p><h1>Subjects</h1><input id="search" type="search" placeholder="Search chapters or formulas" aria-label="Search formulas"></div><div id="subjects-list" class="subject-groups"></div>`); const draw=term=>{const q=term.toLowerCase(); $('#subjects-list').innerHTML=subjects.map((s,i)=>{let groups=chapters(state.formulas.filter(f=>f.subject===s && (!q||f.chapter.toLowerCase().includes(q)||f.title.toLowerCase().includes(q))));return `<section class="subject-group"><h2><span>${['⌗','⚡','⚗'][i]}</span>${s}</h2>${groups.length?groups.map(g=>chapterButton(s,g.chapter,g.items)).join(''):'<p class="empty inline">No matching chapters.</p>'}</section>`}).join(''); document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>navigate('chapter',{subject:b.dataset.subject,chapter:b.dataset.chapter}));}; draw(''); $('#search').oninput=e=>draw(e.target.value);}
const chapters=list=>Object.values(list.reduce((o,f)=>((o[f.chapter]??=[]).push(f),o),{})).map(items=>({chapter:items[0].chapter,items}));
const chapterButton=(subject,chapter,items, tag='')=>`<button class="chapter-row" data-chapter="${esc(chapter)}" data-subject="${esc(subject)}"><div><b>${esc(chapter)}</b><small>${items.length} formula${items.length!==1?'s':''} ${tag}</small></div><i>›</i></button>`;
function chapterPage(){let sel=state.selected||{}, list=state.formulas.filter(f=>f.subject===sel.subject&&(!sel.chapter||f.chapter===sel.chapter)); if(sel.overview){state.selected=null;return navigate('subjects');} if(!list.length)return shell(`<div class="empty"><span>◌</span><h2>No formulas yet</h2><p>This chapter is waiting for its first formula set.</p><button class="primary" data-go="subjects">Browse subjects</button></div>`);let c=counts(list), pct=Math.round(c.reviewed/list.length*100);shell(`<button class="back" data-go="subjects">← Subjects</button><div class="page-title"><p class="eyebrow">${esc(sel.subject)}</p><h1>${esc(sel.chapter)}</h1><p>${list.length} formulas ready for recall</p></div><div class="chapter-progress"><div class="heading"><b>Your progress</b><span>${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div><div class="mini-stats"><span>● ${c.easy} Easy</span><span>● ${c.needPractice} Practice</span><span>● ${c.forgot} Forgot</span></div></div><button class="primary full" id="start">Start Revision <span>→</span></button><section class="formula-list"><h2>In this chapter</h2>${list.map(f=>`<article><span>${f.order||'•'}</span><div><b>${esc(f.title)}</b><small>${esc(f.hint)}</small></div></article>`).join('')}</section>`); $('#start').onclick=()=>startSession(list,`${sel.subject} · ${sel.chapter}`);}
function bucketPage(status){let list=state.formulas.filter(f=>state.progress[f.id]?.status===status), label={easy:'Easy',needPractice:'Need Practice',forgot:'Forgot'}[status];shell(`<div class="page-title"><p class="eyebrow">PERSONAL REVISION</p><h1>${label}</h1><p>${list.length} formula${list.length!==1?'s':''} in this list</p></div>${list.length?`<div class="subject-groups">${subjects.map(s=>{let ch=chapters(list.filter(f=>f.subject===s));return ch.length?`<section class="subject-group"><h2>${esc(s)}</h2>${ch.map(g=>chapterButton(s,g.chapter,g.items,'in your list')).join('')}</section>`:''}).join('')}</div>`:empty(status==='forgot'?'No forgotten formulas':'Nothing here yet',status==='forgot'?'Formulas you mark as forgotten will be ready here for focused revision.':'Rate a formula during revision and it will appear here.')}`);document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{let items=list.filter(f=>f.subject===b.dataset.subject&&f.chapter===b.dataset.chapter);startSession(items,`${b.dataset.subject} · ${b.dataset.chapter}`);});}
const empty=(title,text)=>`<div class="empty"><span>◌</span><h2>${title}</h2><p>${text}</p><button class="primary" data-go="subjects">Start revising</button></div>`;
function startSession(items,title){if(!items.length)return notify('There are no formulas in this selection.',true);state.session={formulaIds:items.map(f=>f.id),currentIndex:0,ratings:{},title,startedAt:Date.now()};try{sessionStorage.setItem('formulus-session',JSON.stringify(state.session));}catch{};state.page='revision'; render();}
function revisionPage(){let s=state.session;if(!s)return navigate('home');let f=state.formulas.find(x=>x.id===s.formulaIds[s.currentIndex]);if(!f)return navigate('home'); let revealed=false; shell(`<button class="back" id="exit">← Exit revision</button><div class="revision-head"><span>${esc(s.title)}</span><b>Formula ${s.currentIndex+1} of ${s.formulaIds.length}</b></div><div class="bar"><i style="width:${(s.currentIndex+1)/s.formulaIds.length*100}%"></i></div><button id="recall-card" class="recall-card" aria-label="Reveal formula"><span class="card-label">HINT</span><h2>${esc(f.hint)}</h2><small>Tap to reveal</small></button><div id="ratings" class="ratings hidden"><button data-rate="easy" class="easy">● Easy</button><button data-rate="needPractice" class="needPractice">● Need Practice</button><button data-rate="forgot" class="forgot">● Forgot</button></div><div class="revision-controls"><button id="previous" ${s.currentIndex===0?'disabled':''}>← Previous</button><button id="next">Next →</button></div>`); let card=$('#recall-card');card.onclick=()=>{revealed=!revealed;card.classList.toggle('revealed',revealed);card.innerHTML=revealed?`<span class="card-label">FORMULA</span><div class="math">${formulaHtml(f.formula)}</div>${f.conditions?`<p>${esc(f.conditions)}</p>`:''}<small>Tap to hide</small>`:`<span class="card-label">HINT</span><h2>${esc(f.hint)}</h2><small>Tap to reveal</small>`;$('#ratings').classList.toggle('hidden',!revealed);}; document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rate(f,b.dataset.rate)); $('#previous').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#exit').onclick=()=>{state.session=null;sessionStorage.removeItem('formulus-session');navigate('home');};}
async function rate(f,status){let b=$(`[data-rate="${status}"]`);if(b?.disabled)return;b.disabled=true;try{let old=state.progress[f.id], now=Date.now(), stats={...state.stats}; if(!old)stats.totalReviewed=(stats.totalReviewed||0)+1; if(old?.status)stats[old.status+'Count']=Math.max(0,(stats[old.status+'Count']||0)-1);stats[status+'Count']=(stats[status+'Count']||0)+1;let gap=dayGap(stats.lastRevisionDate);if(gap>1)stats.currentStreak=1;else if(gap===1)stats.currentStreak=(stats.currentStreak||0)+1;stats.lastRevisionDate=today();let progress={status,attempts:(old?.attempts||0)+1,lastReviewed:now,updatedAt:now};await update(ref(db),{[`userProgress/${state.user.uid}/${f.id}`]:progress,[`userStats/${state.user.uid}`]:stats});state.progress[f.id]=progress;state.stats=stats;state.session.ratings[f.id]=status; move(1);}catch(e){console.error(e);notify('Couldn’t save your rating. Please check your connection and try again.',true);b.disabled=false;}}
function move(dir){let s=state.session;s.currentIndex+=dir;if(s.currentIndex<0)s.currentIndex=0;if(s.currentIndex>=s.formulaIds.length){state.page='complete';render();}else{try{sessionStorage.setItem('formulus-session',JSON.stringify(s));}catch{}render();}}
function completePage(){let s=state.session,c={easy:0,needPractice:0,forgot:0};Object.values(s.ratings).forEach(x=>c[x]++);shell(`<div class="complete"><span>🎉</span><p class="eyebrow">SESSION COMPLETE</p><h1>Great work.</h1><p>${esc(s.title)}</p><b>${Object.keys(s.ratings).length} formulas revised</b><div class="summary"><span class="easy">● Easy <b>${c.easy}</b></span><span class="needPractice">● Need Practice <b>${c.needPractice}</b></span><span class="forgot">● Forgot <b>${c.forgot}</b></span></div><button class="primary full" id="again">Revise again</button><button class="secondary full" data-go="subjects">Back to subjects</button></div>`);$('#again').onclick=()=>{let list=state.formulas.filter(f=>s.formulaIds.includes(f.id));startSession(list,s.title);};}
function quickModal(){modal(`<h2>Quick Revision</h2><p>Build a short revision session.</p><label>Subject<select id="q-subject"><option value="all">All subjects</option>${subjects.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Status<select id="q-status"><option value="all">All formulas</option><option value="easy">Easy</option><option value="needPractice">Need Practice</option><option value="forgot">Forgot</option></select></label><label>Number<select id="q-count"><option value="10">10 formulas</option><option value="20">20 formulas</option><option value="30">30 formulas</option><option value="50">50 formulas</option><option value="all">All available</option></select></label><button id="q-start" class="primary full">Start revision</button>`);$('#q-start').onclick=()=>{let sub=$('#q-subject').value,status=$('#q-status').value,n=$('#q-count').value;let a=state.formulas.filter(f=>(sub==='all'||f.subject===sub)&&(status==='all'||state.progress[f.id]?.status===status)).sort(()=>Math.random()-.5);closeModal();startSession(n==='all'?a:a.slice(0,+n),'Quick Revision');};}
function profile(){let c=counts();shell(`<div class="page-title"><p class="eyebrow">YOUR ACCOUNT</p><h1>Profile</h1></div><div class="profile"><img src="${esc(state.user.photoURL||'')}" alt="" onerror="this.style.display='none'"><div><h2>${esc(state.user.displayName||'Student')}</h2><p>${esc(state.user.email||'')}</p></div></div><div class="profile-stats"><div><b>${state.stats.currentStreak||0}</b><small>Day streak</small></div><div><b>${state.stats.totalReviewed||0}</b><small>Reviewed</small></div></div><div class="setting-list"><div><span class="easy">●</span> Easy <b>${c.easy}</b></div><div><span class="needPractice">●</span> Need Practice <b>${c.needPractice}</b></div><div><span class="forgot">●</span> Forgot <b>${c.forgot}</b></div></div><button id="signout" class="secondary full">Sign out</button><button id="reset" class="danger-link">Reset my progress</button>`);$('#signout').onclick=()=>signOut(auth);$('#reset').onclick=()=>{modal(`<h2>Reset your progress?</h2><p>This permanently removes only your ratings and revision statistics. Formula content will not be affected.</p><button id="confirm-reset" class="danger full">Reset my progress</button>`);$('#confirm-reset').onclick=async()=>{try{await Promise.all([remove(ref(db,`userProgress/${state.user.uid}`)),remove(ref(db,`userStats/${state.user.uid}`))]);state.progress={};state.stats=blankStats();closeModal();navigate('profile');}catch{notify('Couldn’t reset progress. Please try again.',true);}};};}
function admin(){shell(`<div class="page-title"><p class="eyebrow">ADMIN ONLY</p><h1>Formula management</h1><p>Import a full chapter or manage existing formulas.</p></div><section class="admin-form"><label>Subject<select id="a-subject">${subjects.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Chapter<input id="a-chapter" placeholder="e.g. Differential Equations"></label><label>Formula data (JSON)<textarea id="a-json" rows="10" placeholder='[{"title":"...","hint":"...","formula":"...","conditions":""}]'></textarea></label><button id="validate" class="secondary">Validate & preview</button><div id="import-feedback"></div></section><section class="formula-list"><h2>Existing chapters</h2>${state.formulas.length?chapters(state.formulas).map(g=>`<article><div><b>${esc(g.items[0].subject)} · ${esc(g.chapter)}</b><small>${g.items.length} formulas</small></div><button class="text manage" data-subject="${esc(g.items[0].subject)}" data-chapter="${esc(g.chapter)}">Manage</button></article>`).join(''):empty('No formula sets yet','Import your first chapter above.')}</section>`);$('#validate').onclick=validateImport;document.querySelectorAll('.manage').forEach(b=>b.onclick=()=>manageChapter(b.dataset.subject,b.dataset.chapter));}
function parseImport(){let subject=$('#a-subject').value,chapter=$('#a-chapter').value.trim(),raw=$('#a-json').value;let data;try{data=JSON.parse(raw);}catch{throw Error('The formula data is not valid JSON.');}if(!chapter)throw Error('Enter a chapter name.');if(!Array.isArray(data)||!data.length)throw Error('Provide a non-empty JSON array.');data.forEach((x,i)=>{if(!x||typeof x!=='object'||['title','hint','formula'].some(k=>typeof x[k]!=='string'||!x[k].trim()))throw Error(`Formula #${i+1} needs a title, hint, and formula (all strings).`);});return {subject,chapter,data};}
function validateImport(){let box=$('#import-feedback');try{let x=parseImport();box.innerHTML=`<div class="preview"><b>Import preview</b><p>${esc(x.subject)} · ${esc(x.chapter)} · ${x.data.length} formulas</p><ol>${x.data.slice(0,8).map(f=>`<li>${esc(f.title)}</li>`).join('')}</ol><button id="import" class="primary">Import ${x.data.length} formulas</button></div>`;$('#import').onclick=()=>importSet(x);}catch(e){box.innerHTML=`<p class="error-msg">${esc(e.message)}</p>`;}}
async function importSet(x){let existing=state.formulas.filter(f=>f.subject===x.subject&&f.chapter===x.chapter);if(existing.length){modal(`<h2>Chapter already exists</h2><p>This chapter has ${existing.length} formulas. Choose how to continue.</p><button id="add" class="primary full">Add to existing chapter</button><button id="replace" class="danger full">Replace existing chapter</button>`);$('#add').onclick=()=>writeSet(x,false);$('#replace').onclick=()=>writeSet(x,true);return;}writeSet(x,false);}
async function writeSet(x,replace){try{if(replace){let safe=chapterKey(x.chapter);await remove(ref(db,`formulas/${x.subject}/${safe}`));}let base=ref(db,`formulas/${x.subject}/${chapterKey(x.chapter)}`), writes={};x.data.forEach((f,i)=>{let id=push(base).key;writes[`formulas/${x.subject}/${chapterKey(x.chapter)}/${id}`]={id,subject:x.subject,chapter:x.chapter,title:f.title.trim(),hint:f.hint.trim(),formula:f.formula.trim(),conditions:(f.conditions||'').trim(),order:i+1,createdAt:Date.now(),updatedAt:Date.now()};});await update(ref(db),writes);closeModal();await loadData();notify(`${x.data.length} formulas imported.`);navigate('admin');}catch(e){console.error(e);notify('Import failed. Check your permissions and connection.',true);}}
const chapterKey=x=>x.trim().replace(/[.#$\[\]/]/g,'_');
function manageChapter(subject,chapter){let list=state.formulas.filter(f=>f.subject===subject&&f.chapter===chapter);modal(`<h2>${esc(chapter)}</h2><p>${esc(subject)}</p><div class="manage-list">${list.map(f=>`<div><b>${esc(f.title)}</b><span><button class="edit" data-id="${f.id}">Edit</button><button class="del" data-id="${f.id}">Delete</button></span></div>`).join('')}</div>`);document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editFormula(state.formulas.find(f=>f.id===b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteFormula(state.formulas.find(f=>f.id===b.dataset.id)));}
function editFormula(f){modal(`<h2>Edit formula</h2><label>Title<input id="e-title" value="${esc(f.title)}"></label><label>Hint<textarea id="e-hint">${esc(f.hint)}</textarea></label><label>Formula (LaTex)<textarea id="e-formula">${esc(f.formula)}</textarea></label><div class="preview math">${formulaHtml(f.formula)}</div><label>Conditions<input id="e-conditions" value="${esc(f.conditions||'')}"></label><label>Order<input id="e-order" type="number" value="${f.order||1}"></label><button id="save-edit" class="primary full">Save changes</button>`);$('#e-formula').oninput=e=>$('.preview').innerHTML=formulaHtml(e.target.value);$('#save-edit').onclick=async()=>{try{await update(ref(db,`formulas/${f.subject}/${chapterKey(f.chapter)}/${f.id}`),{title:$('#e-title').value.trim(),hint:$('#e-hint').value.trim(),formula:$('#e-formula').value.trim(),conditions:$('#e-conditions').value.trim(),order:+$('#e-order').value||1,updatedAt:Date.now()});await loadData();closeModal();notify('Formula updated.');navigate('admin');}catch{notify('Couldn’t save changes.',true);}};}
function deleteFormula(f){modal(`<h2>Delete “${esc(f.title)}”?</h2><p>This removes the formula from the global chapter. Existing personal progress may remain but will no longer be displayed.</p><button id="confirm-delete" class="danger full">Delete formula</button>`);$('#confirm-delete').onclick=async()=>{try{await remove(ref(db,`formulas/${f.subject}/${chapterKey(f.chapter)}/${f.id}`));await loadData();closeModal();notify('Formula deleted.');navigate('admin');}catch{notify('Couldn’t delete formula.',true);}};}
function modal(body){let x=document.createElement('div');x.className='modal-backdrop';x.id='modal';x.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Close">×</button>${body}</div>`;document.body.append(x);x.querySelector('.close').onclick=closeModal;x.onclick=e=>{if(e.target===x)closeModal();};}
function closeModal(){$('#modal')?.remove();}
async function aiPromptModal(){modal(`<h2>Prompt for AIs</h2><p>Copy this prompt, then paste it into an AI along with your study material.</p><textarea id="ai-prompt-text" class="ai-prompt-text" readonly aria-label="Formulus formula extraction prompt">Loading prompt…</textarea><button id="copy-ai-prompt" class="primary full" disabled>Copy prompt</button>`);const field=$('#ai-prompt-text'),copy=$('#copy-ai-prompt');try{const response=await fetch('./assets/formulus-ai-prompt.txt');if(!response.ok)throw Error('Prompt unavailable');const prompt=await response.text();field.value=prompt;copy.disabled=false;copy.onclick=async()=>{try{await navigator.clipboard.writeText(prompt);notify('Prompt copied to your clipboard.');}catch{field.focus();field.select();try{document.execCommand('copy');notify('Prompt copied to your clipboard.');}catch{notify('Select and copy the prompt manually.',true);}}};}catch{field.value='The prompt could not be loaded.';notify('Couldn’t load the AI prompt.',true);}}
new MutationObserver(()=>{if(state.page!=='profile'||$('#ai-prompt-option'))return;const signout=$('#signout');if(!signout)return;const option=document.createElement('button');option.id='ai-prompt-option';option.className='secondary full';option.textContent='Prompt for AIs';option.onclick=aiPromptModal;signout.before(option);}).observe(app,{childList:true,subtree:true});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(state.page==='revision'){if(e.code==='Space'||e.code==='Enter'){$('#recall-card')?.click();e.preventDefault();}if(e.key==='ArrowRight')$('#next')?.click();if(e.key==='ArrowLeft')$('#previous')?.click();if(['1','2','3'].includes(e.key))$(`[data-rate="${['easy','needPractice','forgot'][+e.key-1]}"]`)?.click();}});
window.addEventListener('online',()=>notify('You’re back online.'));window.addEventListener('offline',()=>notify('You’re offline. Ratings will need a connection to save.',true));
if ('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(error=>console.warn('Service worker registration failed',error)));
getRedirectResult(auth).catch(e=>{console.error(e);notify('Couldn’t complete Google sign-in.',true);});
onAuthStateChanged(auth,user=>{if(user)bootstrap(user);else{state.user=null;state.formulas=[];state.progress={};login();}});
